#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
  resource: '../src/Controller/'
  type: annotation
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'


jmose_command_scheduler:
  resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'