# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'de'
    app_locales: de|en
    upload_directory: '%kernel.project_dir%/public/uploads/images'
    extension_directory: '%kernel.project_dir%/public/uploads/tbs-extension'
    tbs_content_element_directory: '%kernel.project_dir%/public/typo3-ce-extension'
    tbs_content_element_directory_project: '/typo3-ce-extension/tbs_content_elements_project'
    tbs_content_element_directory_project_init: '/typo3-ce-extension/tbs_content_elements'
    tbs_content_element_directory_tsconfig: '/typo3-ce-extension/tbs_content_elements/Configuration/TsConfig/Mod/TBS-Module/'
    tbs_content_element_directory_typoscript: '/typo3-ce-extension/tbs_content_elements/Configuration/TypoScript/Frontend/TBS-Module/'
    tbs_content_element_directory_tt_content: '/typo3-ce-extension/tbs_content_elements/Configuration/TCA/Overrides/TBS-Module/'
    tbs_content_element_directory_tt_content_override: '/typo3-ce-extension/tbs_content_elements/Configuration/TCA/Overrides/'
    tbs_content_element_directory_sql: '/typo3-ce-extension/tbs_content_elements/'
    tbs_content_element_directory_html_backend: '/typo3-ce-extension/tbs_content_elements/Resources/Private/Backend/Templates/'
    tbs_content_element_directory_html_frontend: '/typo3-ce-extension/tbs_content_elements/Resources/Private/Templates/'
    tbs_content_element_directory_language: '/typo3-ce-extension/tbs_content_elements/Resources/Private/Language/'
    tbs_content_element_directory_backend_preview_php: '/typo3-ce-extension/tbs_content_elements_project/Classes/Hooks/PageLayoutView/'
    tbs_content_element_directory_download: '%kernel.project_dir%/public'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\RedirectToLocaleSubscriber:
        arguments: [ '@router', '%app_locales%', '%locale%' ]

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%upload_directory%'

    kernel.listener.prefix:
        class: App\EventListener\TablePrefixEventListener
        # Adding the table_prefix configuration
        calls:
            - [ setConfig, [ '%table_prefix%' ] ]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, method: loadClassMetadata }


